spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: student
      username: root
      password: 1234
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}?authSource=admin
